name: AutoGerar NBA

on:
  schedule:
    - cron: '30 12 * * *'  # 12:30 UTC = 09:30 Brasília
  workflow_dispatch:  # Execução manual

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Instalar Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Instalar dependências
      run: |
        pip install selenium requests
    
    - name: Executar automação NBA
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        LOGIN: ${{ secrets.LOGIN }}
        SENHA: ${{ secrets.SENHA }}
      run: python main.py
    
    - name: Upload prints NBA
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-nba
        path: prints/
        if-no-files-found: ignore
